### ISSUE TITLE
Error: `ldconfig -p` contains duplicates

### ISSUE THREAD

**Issue by SolarAquarion** [dimgel/check-link-consistency#1]
FilesCollector:373: `ldconfig -p` line 6523: error {`libOpenCL.so.1`, 64-bit}: duplicate key

**Comment by dimgel** [comment]
Please attach full output of `ldconfig -p`.

**Comment by curable-online** [comment]
Can we make it someway to ignore duplicated keys?

**Comment by curable-online** [comment]
Running this: `sudo check-link-consistency -v` Results in this:
```
ERR   FilesCollector:377: `ldconfig -p` line 1400: error {`libtbbmalloc_proxy.so.2`, 64-bit}: duplicate key
```
Then running this: `ldconfig -p | grep -i libtbbmalloc_proxy.so.2` Results in this:
```
libtbbmalloc_proxy.so.2 (libc6,x86-64) => /opt/intel/oneapi/tbb/latest/lib/intel64/gcc4.8/libtbbmalloc_proxy.so.2
libtbbmalloc_proxy.so.2 (libc6,x86-64) => /usr/lib/libtbbmalloc_proxy.so.2
```
Then running this: 
```
pacman -Qo /opt/intel/oneapi/tbb/latest/lib/intel64/gcc4.8/libtbbmalloc_proxy.so.2
```
Resutls in this:
```
/opt/intel/oneapi/tbb/2021.10.0/lib/intel64/gcc4.8/libtbbmalloc_proxy.so.2 is owned by intel-oneapi-tbb 2021.10.0-3.1
```
Which is a repository package.

Also running this:
```
pacman -Qo /usr/lib/libtbbmalloc_proxy.so.2
```
Results in this:
```
/usr/lib/libtbbmalloc_proxy.so.2 is owned by onetbb 2021.10.0-1.1
```
That is also a repo package of Arch.


So simply I don't know what should I do now.

**Comment by curable-online** [comment]
Both `onetbb` and `intel-oneapi-tbb` packages are required by many other packages.

**Comment by dimgel** [comment]
> Both `onetbb` and `intel-oneapi-tbb` packages are required by many other packages.

This is obviously a mess. I don't know how the system chooses among these two libs, my guess it takes just first one it sees. But if check-link-consistency did the same, such behaviour would competely violate its very goal: to detect messes. I could show error message, then remove duplication and continue, but if 2 libs are actually different then user might get false positives or undetected errors. And comparing two lib files for strict equality feels stupid too: handling rare subcase of rare case with motivation "wait a moment, maybe this mess would actually do".  

UPD: And even 2 lib files are the same, their RPATH may contain relative paths to other libs which might NOT be same.

So I don't feel like doing anything about it. "Not a bug."

**Comment by curable-online** [comment]
Well may not be considered as a bug. But the program stops and the command exits. (I don't remember the exit code and I can't reproduce it because I have removed the duplicated libraries)
Is that intended? Shouldn't it keep processing and giving all results and problems at the end instead of exiting for each error?

**Comment by SolarAquarion** [comment]
> Please attach full output of `ldconfig -p`.

	libiomp5_db.so (libc6,x86-64) => /opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin/libiomp5_db.so
	libiomp5_db.so (libc6,x86-64) => /opt/intel/oneapi/lib/intel64/libiomp5_db.so

**Comment by dimgel** [comment]
I've finally hit same problem after installing package `cuda`, and found out empirically (i.e. no guarantee it's correct) that when ld.so.cache contains duplicated keys then `ldd` takes first entry it finds, in the same order as `ldconfig -p` outputs. So do I now.

Fixed?
