### ISSUE TITLE
Another Error: `ldconfig -p` output contains localized text

### ISSUE THREAD

**Issue by Mookiiii** [dimgel/check-link-consistency#2]
I got an error when running: 

`EXEC  /usr/bin/ldconfig -p
ERR   FilesCollector:279: `ldconfig -p` line 1: could not parse`

ldconfig -p output :
[ldconfig.txt](https://github.com/dimgel/check-link-consistency/files/12380207/ldconfig.txt)

Thanks

**Comment by dimgel** [comment]
Ha. :) So, should I probably ignore 1st line (localized text) except 1st number? And last line too, maybe except checking it starts at column 1 and contains " ldconfig ".

Currently: 
1st line regex: https://github.com/dimgel/check-link-consistency/blob/5b23e019733aa29d46d4ec50750e5bd505bd5f6c/src/main/FilesCollector.cpp#L272
last line regex: https://github.com/dimgel/check-link-consistency/blob/5b23e019733aa29d46d4ec50750e5bd505bd5f6c/src/main/FilesCollector.cpp#L388

**Comment by dimgel** [comment]
Try now.

**Comment by Mookiiii** [comment]
Sorry for the late response.. 

Yes, now its working fine without errors.

Thank you :-)
